@setlocal
@echo off

call "%~dp0\test-config.bat"

rem テスト対象
set TEST_TARGET_PATH="%TEST_BAT_DIR%\FileBatchProcessing.bat"

rem テンポラリ
set time2=%time: =0%
set TEST_TEMP_DIR_2=%TEST_TEMP_DIR%\FileBatchProcessing_Test%date:~0,4%%date:~5,2%%date:~8,2%%time2:~0,2%%time2:~3,2%%time2:~6,2%%time2:~9,2%

set LOGGER_HANDLER=console

rem 1 正常に処理できた場合、0を返す(対象フォルダ：引数)
rem テストパターン
rem 1-1 [ファイル：複数] [対象フォルダ：引数、拡張子：引数、バッチ引数：指定]
set TEST_NO=1-1
set TEST_DIR_PATH=%TEST_TEMP_DIR_2%\%TEST_NO%
call :Test1 "%TEST_DIR_PATH%"
call %TEST_TARGET_PATH% "%~dp0\FileBatchProcessing\%TEST_NO%.properties" "%TEST_DIR_PATH%" "*.txt" "arg1 arg2"
call %TEST_ASSERT_EQUALS% TEST%TEST_NO% 0 %ERRORLEVEL%
call %TEST_ASSERT_FILE_FIRST_LINE_EQUALS% TEST%TEST_NO%_1 "arg1,arg2" "%TEST_DIR_PATH%\1.txt"
call %TEST_ASSERT_FILE_FIRST_LINE_EQUALS% TEST%TEST_NO%_2 "b" "%TEST_DIR_PATH%\2.jpg"
call %TEST_ASSERT_FILE_FIRST_LINE_EQUALS% TEST%TEST_NO%_3 "arg1,arg2" "%TEST_DIR_PATH%\3.txt"
call %TEST_ASSERT_FILE_FIRST_LINE_EQUALS% TEST%TEST_NO%_4 "arg1,arg2" "%TEST_DIR_PATH%\4.txt"
call %TEST_ASSERT_FILE_FIRST_LINE_EQUALS% TEST%TEST_NO%_5 "e" "%TEST_DIR_PATH%\5"
call %TEST_ASSERT_FILE_FIRST_LINE_EQUALS% TEST%TEST_NO%_6 "f" "%TEST_DIR_PATH%\6.gif"

rem 1-2 [ファイル：単一] [対象フォルダ：引数、拡張子：プロパティ、バッチ引数：指定]
set TEST_NO=1-2
set TEST_DIR_PATH=%TEST_TEMP_DIR_2%\%TEST_NO%
call :Test1 "%TEST_DIR_PATH%"
call %TEST_TARGET_PATH% "%~dp0\FileBatchProcessing\%TEST_NO%.properties" "%TEST_DIR_PATH%" "" "arg1 arg2"
call %TEST_ASSERT_EQUALS% TEST%TEST_NO% 0 %ERRORLEVEL%
call %TEST_ASSERT_FILE_FIRST_LINE_EQUALS% TEST%TEST_NO%_1 "a" "%TEST_DIR_PATH%\1.txt"
call %TEST_ASSERT_FILE_FIRST_LINE_EQUALS% TEST%TEST_NO%_2 "arg1,arg2" "%TEST_DIR_PATH%\2.jpg"
call %TEST_ASSERT_FILE_FIRST_LINE_EQUALS% TEST%TEST_NO%_3 "c" "%TEST_DIR_PATH%\3.txt"
call %TEST_ASSERT_FILE_FIRST_LINE_EQUALS% TEST%TEST_NO%_4 "d" "%TEST_DIR_PATH%\4.txt"
call %TEST_ASSERT_FILE_FIRST_LINE_EQUALS% TEST%TEST_NO%_5 "e" "%TEST_DIR_PATH%\5"
call %TEST_ASSERT_FILE_FIRST_LINE_EQUALS% TEST%TEST_NO%_6 "f" "%TEST_DIR_PATH%\6.gif"

rem 1-3 [ファイル：複数] [対象フォルダ：引数、拡張子：未指定、バッチ引数：指定]
set TEST_NO=1-3
set TEST_DIR_PATH=%TEST_TEMP_DIR_2%\%TEST_NO%
call :Test1 "%TEST_DIR_PATH%"
call %TEST_TARGET_PATH% "%~dp0\FileBatchProcessing\%TEST_NO%.properties" "%TEST_DIR_PATH%" "" "arg1 arg2"
call %TEST_ASSERT_EQUALS% TEST%TEST_NO% 0 %ERRORLEVEL%
call %TEST_ASSERT_FILE_FIRST_LINE_EQUALS% TEST%TEST_NO%_1 "arg1,arg2" "%TEST_DIR_PATH%\1.txt"
call %TEST_ASSERT_FILE_FIRST_LINE_EQUALS% TEST%TEST_NO%_2 "arg1,arg2" "%TEST_DIR_PATH%\2.jpg"
call %TEST_ASSERT_FILE_FIRST_LINE_EQUALS% TEST%TEST_NO%_3 "arg1,arg2" "%TEST_DIR_PATH%\3.txt"
call %TEST_ASSERT_FILE_FIRST_LINE_EQUALS% TEST%TEST_NO%_4 "arg1,arg2" "%TEST_DIR_PATH%\4.txt"
call %TEST_ASSERT_FILE_FIRST_LINE_EQUALS% TEST%TEST_NO%_5 "arg1,arg2" "%TEST_DIR_PATH%\5"
call %TEST_ASSERT_FILE_FIRST_LINE_EQUALS% TEST%TEST_NO%_6 "arg1,arg2" "%TEST_DIR_PATH%\6.gif"

rem 1-4 [ファイル：単一] [対象フォルダ：引数、拡張子：引数、バッチ引数：未指定]
set TEST_NO=1-4
set TEST_DIR_PATH=%TEST_TEMP_DIR_2%\%TEST_NO%
call :Test1 "%TEST_DIR_PATH%"
call %TEST_TARGET_PATH% "%~dp0\FileBatchProcessing\%TEST_NO%.properties" "%TEST_DIR_PATH%" "5" "arg1 arg2"
call %TEST_ASSERT_EQUALS% TEST%TEST_NO% 0 %ERRORLEVEL%
call %TEST_ASSERT_FILE_FIRST_LINE_EQUALS% TEST%TEST_NO%_1 "a" "%TEST_DIR_PATH%\1.txt"
call %TEST_ASSERT_FILE_FIRST_LINE_EQUALS% TEST%TEST_NO%_2 "b" "%TEST_DIR_PATH%\2.jpg"
call %TEST_ASSERT_FILE_FIRST_LINE_EQUALS% TEST%TEST_NO%_3 "c" "%TEST_DIR_PATH%\3.txt"
call %TEST_ASSERT_FILE_FIRST_LINE_EQUALS% TEST%TEST_NO%_4 "d" "%TEST_DIR_PATH%\4.txt"
call %TEST_ASSERT_FILE_FIRST_LINE_EQUALS% TEST%TEST_NO%_5 "arg1,arg2" "%TEST_DIR_PATH%\5"
call %TEST_ASSERT_FILE_FIRST_LINE_EQUALS% TEST%TEST_NO%_6 "f" "%TEST_DIR_PATH%\6.gif"

rem 1-5 [ファイル：無し] [対象フォルダ：引数、拡張子：プロパティ、バッチ引数：未指定]
set TEST_NO=1-5
set TEST_DIR_PATH=%TEST_TEMP_DIR_2%\%TEST_NO%
call :Test1 "%TEST_DIR_PATH%"
call %TEST_TARGET_PATH% "%~dp0\FileBatchProcessing\%TEST_NO%.properties" "%TEST_DIR_PATH%"
call %TEST_ASSERT_EQUALS% TEST%TEST_NO% 0 %ERRORLEVEL%
call %TEST_ASSERT_FILE_FIRST_LINE_EQUALS% TEST%TEST_NO%_1 "a" "%TEST_DIR_PATH%\1.txt"
call %TEST_ASSERT_FILE_FIRST_LINE_EQUALS% TEST%TEST_NO%_2 "b" "%TEST_DIR_PATH%\2.jpg"
call %TEST_ASSERT_FILE_FIRST_LINE_EQUALS% TEST%TEST_NO%_3 "c" "%TEST_DIR_PATH%\3.txt"
call %TEST_ASSERT_FILE_FIRST_LINE_EQUALS% TEST%TEST_NO%_4 "d" "%TEST_DIR_PATH%\4.txt"
call %TEST_ASSERT_FILE_FIRST_LINE_EQUALS% TEST%TEST_NO%_5 "e" "%TEST_DIR_PATH%\5"
call %TEST_ASSERT_FILE_FIRST_LINE_EQUALS% TEST%TEST_NO%_6 "f" "%TEST_DIR_PATH%\6.gif"

rem 1-6 [ファイル：複数] [対象フォルダ：引数、拡張子：未指定、バッチ引数：未指定]
set TEST_NO=1-6
set TEST_DIR_PATH=%TEST_TEMP_DIR_2%\%TEST_NO%
call :Test1 "%TEST_DIR_PATH%"
call %TEST_TARGET_PATH% "%~dp0\FileBatchProcessing\%TEST_NO%.properties" "%TEST_DIR_PATH%"
call %TEST_ASSERT_EQUALS% TEST%TEST_NO% 0 %ERRORLEVEL%
call %TEST_ASSERT_FILE_FIRST_LINE_EQUALS% TEST%TEST_NO%_1 "xxx,yyy" "%TEST_DIR_PATH%\1.txt"
call %TEST_ASSERT_FILE_FIRST_LINE_EQUALS% TEST%TEST_NO%_2 "xxx,yyy" "%TEST_DIR_PATH%\2.jpg"
call %TEST_ASSERT_FILE_FIRST_LINE_EQUALS% TEST%TEST_NO%_3 "xxx,yyy" "%TEST_DIR_PATH%\3.txt"
call %TEST_ASSERT_FILE_FIRST_LINE_EQUALS% TEST%TEST_NO%_4 "xxx,yyy" "%TEST_DIR_PATH%\4.txt"
call %TEST_ASSERT_FILE_FIRST_LINE_EQUALS% TEST%TEST_NO%_5 "xxx,yyy" "%TEST_DIR_PATH%\5"
call %TEST_ASSERT_FILE_FIRST_LINE_EQUALS% TEST%TEST_NO%_6 "xxx,yyy" "%TEST_DIR_PATH%\6.gif"

rem 2 正常に処理できた場合、0を返す(対象フォルダ：プロパティ)
rem 2-1 [ファイル：複数] [対象フォルダ：プロパティ、拡張子：引数、バッチ引数：引数]
set TEST_NO=2-1
set TEST_DIR_PATH=%TEST_TEMP_DIR_2%\%TEST_NO%
call :Test1 "%TEST_DIR_PATH%"
call %TEST_TARGET_PATH% "%~dp0\FileBatchProcessing\%TEST_NO%.properties" "%TEST_DIR_PATH%" "*.txt" "arg1 arg2"
call %TEST_ASSERT_EQUALS% TEST%TEST_NO% 0 %ERRORLEVEL%
call %TEST_ASSERT_FILE_FIRST_LINE_EQUALS% TEST%TEST_NO%_1 "arg1,arg2" "%TEST_DIR_PATH%\1.txt"
call %TEST_ASSERT_FILE_FIRST_LINE_EQUALS% TEST%TEST_NO%_2 "b" "%TEST_DIR_PATH%\2.jpg"
call %TEST_ASSERT_FILE_FIRST_LINE_EQUALS% TEST%TEST_NO%_3 "arg1,arg2" "%TEST_DIR_PATH%\3.txt"
call %TEST_ASSERT_FILE_FIRST_LINE_EQUALS% TEST%TEST_NO%_4 "arg1,arg2" "%TEST_DIR_PATH%\4.txt"
call %TEST_ASSERT_FILE_FIRST_LINE_EQUALS% TEST%TEST_NO%_5 "e" "%TEST_DIR_PATH%\5"
call %TEST_ASSERT_FILE_FIRST_LINE_EQUALS% TEST%TEST_NO%_6 "f" "%TEST_DIR_PATH%\6.gif"

rem 2-2 [ファイル：複数] [対象フォルダ：プロパティ、拡張子：プロパティ、バッチ引数：引数]
set TEST_NO=2-2
set TEST_DIR_PATH=%TEST_TEMP_DIR_2%\%TEST_NO%
call :Test1 "%TEST_DIR_PATH%"
call %TEST_TARGET_PATH% "%~dp0\FileBatchProcessing\%TEST_NO%.properties" "%TEST_DIR_PATH%" "" "arg1 arg2"
call %TEST_ASSERT_EQUALS% TEST%TEST_NO% 0 %ERRORLEVEL%
call %TEST_ASSERT_FILE_FIRST_LINE_EQUALS% TEST%TEST_NO%_1 "arg1,arg2" "%TEST_DIR_PATH%\1.txt"
call %TEST_ASSERT_FILE_FIRST_LINE_EQUALS% TEST%TEST_NO%_2 "b" "%TEST_DIR_PATH%\2.jpg"
call %TEST_ASSERT_FILE_FIRST_LINE_EQUALS% TEST%TEST_NO%_3 "arg1,arg2" "%TEST_DIR_PATH%\3.txt"
call %TEST_ASSERT_FILE_FIRST_LINE_EQUALS% TEST%TEST_NO%_4 "arg1,arg2" "%TEST_DIR_PATH%\4.txt"
call %TEST_ASSERT_FILE_FIRST_LINE_EQUALS% TEST%TEST_NO%_5 "e" "%TEST_DIR_PATH%\5"
call %TEST_ASSERT_FILE_FIRST_LINE_EQUALS% TEST%TEST_NO%_6 "f" "%TEST_DIR_PATH%\6.gif"

rem 3 プロパティファイルの読み込みに失敗した場合、1を返す
set TEST_NO=3
set TEST_DIR_PATH=%TEST_TEMP_DIR_2%\%TEST_NO%
call :Test1 "%TEST_DIR_PATH%"
call %TEST_TARGET_PATH% "%~dp0\FileBatchProcessing\%TEST_NO%.properties" "%TEST_DIR_PATH%" "*.txt" "arg1 arg2"
call %TEST_ASSERT_EQUALS% TEST%TEST_NO% 1 %ERRORLEVEL%
call %TEST_ASSERT_FILE_FIRST_LINE_EQUALS% TEST%TEST_NO%_1 "a" "%TEST_DIR_PATH%\1.txt"
call %TEST_ASSERT_FILE_FIRST_LINE_EQUALS% TEST%TEST_NO%_2 "b" "%TEST_DIR_PATH%\2.jpg"
call %TEST_ASSERT_FILE_FIRST_LINE_EQUALS% TEST%TEST_NO%_3 "c" "%TEST_DIR_PATH%\3.txt"
call %TEST_ASSERT_FILE_FIRST_LINE_EQUALS% TEST%TEST_NO%_4 "d" "%TEST_DIR_PATH%\4.txt"
call %TEST_ASSERT_FILE_FIRST_LINE_EQUALS% TEST%TEST_NO%_5 "e" "%TEST_DIR_PATH%\5"
call %TEST_ASSERT_FILE_FIRST_LINE_EQUALS% TEST%TEST_NO%_6 "f" "%TEST_DIR_PATH%\6.gif"

rem 4 プロパティファイルの内容が不正の場合、2を返す
rem 4-1 対象フォルダ
set TEST_NO=4-1
set TEST_DIR_PATH=%TEST_TEMP_DIR_2%\%TEST_NO%
call :Test1 "%TEST_DIR_PATH%"
call %TEST_TARGET_PATH% "%~dp0\FileBatchProcessing\%TEST_NO%.properties" "" "*.txt" "arg1 arg2"
call %TEST_ASSERT_EQUALS% TEST%TEST_NO% 2 %ERRORLEVEL%
call %TEST_ASSERT_FILE_FIRST_LINE_EQUALS% TEST%TEST_NO%_1 "a" "%TEST_DIR_PATH%\1.txt"
call %TEST_ASSERT_FILE_FIRST_LINE_EQUALS% TEST%TEST_NO%_2 "b" "%TEST_DIR_PATH%\2.jpg"
call %TEST_ASSERT_FILE_FIRST_LINE_EQUALS% TEST%TEST_NO%_3 "c" "%TEST_DIR_PATH%\3.txt"
call %TEST_ASSERT_FILE_FIRST_LINE_EQUALS% TEST%TEST_NO%_4 "d" "%TEST_DIR_PATH%\4.txt"
call %TEST_ASSERT_FILE_FIRST_LINE_EQUALS% TEST%TEST_NO%_5 "e" "%TEST_DIR_PATH%\5"
call %TEST_ASSERT_FILE_FIRST_LINE_EQUALS% TEST%TEST_NO%_6 "f" "%TEST_DIR_PATH%\6.gif"

rem 4-2 対象ファイルに対して実行する外部バッチファイル
set TEST_NO=4-2
set TEST_DIR_PATH=%TEST_TEMP_DIR_2%\%TEST_NO%
call :Test1 "%TEST_DIR_PATH%"
call %TEST_TARGET_PATH% "%~dp0\FileBatchProcessing\%TEST_NO%.properties" "%TEST_DIR_PATH%" "*.txt" "arg1 arg2"
call %TEST_ASSERT_EQUALS% TEST%TEST_NO% 2 %ERRORLEVEL%
call %TEST_ASSERT_FILE_FIRST_LINE_EQUALS% TEST%TEST_NO%_1 "a" "%TEST_DIR_PATH%\1.txt"
call %TEST_ASSERT_FILE_FIRST_LINE_EQUALS% TEST%TEST_NO%_2 "b" "%TEST_DIR_PATH%\2.jpg"
call %TEST_ASSERT_FILE_FIRST_LINE_EQUALS% TEST%TEST_NO%_3 "c" "%TEST_DIR_PATH%\3.txt"
call %TEST_ASSERT_FILE_FIRST_LINE_EQUALS% TEST%TEST_NO%_4 "d" "%TEST_DIR_PATH%\4.txt"
call %TEST_ASSERT_FILE_FIRST_LINE_EQUALS% TEST%TEST_NO%_5 "e" "%TEST_DIR_PATH%\5"
call %TEST_ASSERT_FILE_FIRST_LINE_EQUALS% TEST%TEST_NO%_6 "f" "%TEST_DIR_PATH%\6.gif"

rem 5 引数が不正の場合、8を返す
rem 5-1 プロパティファイル
set TEST_NO=5-1
set TEST_DIR_PATH=%TEST_TEMP_DIR_2%\%TEST_NO%
call :Test1 "%TEST_DIR_PATH%"
call %TEST_TARGET_PATH% "" "%TEST_DIR_PATH%" "*.txt" "arg1 arg2"
call %TEST_ASSERT_EQUALS% TEST%TEST_NO% 8 %ERRORLEVEL%
call %TEST_ASSERT_FILE_FIRST_LINE_EQUALS% TEST%TEST_NO%_1 "a" "%TEST_DIR_PATH%\1.txt"
call %TEST_ASSERT_FILE_FIRST_LINE_EQUALS% TEST%TEST_NO%_2 "b" "%TEST_DIR_PATH%\2.jpg"
call %TEST_ASSERT_FILE_FIRST_LINE_EQUALS% TEST%TEST_NO%_3 "c" "%TEST_DIR_PATH%\3.txt"
call %TEST_ASSERT_FILE_FIRST_LINE_EQUALS% TEST%TEST_NO%_4 "d" "%TEST_DIR_PATH%\4.txt"
call %TEST_ASSERT_FILE_FIRST_LINE_EQUALS% TEST%TEST_NO%_5 "e" "%TEST_DIR_PATH%\5"
call %TEST_ASSERT_FILE_FIRST_LINE_EQUALS% TEST%TEST_NO%_6 "f" "%TEST_DIR_PATH%\6.gif"

rem 6 外部バッチファイルでエラーが発生した場合
rem 6-1 3ファイルのうち1ファイル目でエラーが発生し処理を継続しない
set TEST_NO=6-1
set TEST_DIR_PATH=%TEST_TEMP_DIR_2%\%TEST_NO%
call :Test1 "%TEST_DIR_PATH%"
call %TEST_TARGET_PATH% "%~dp0\FileBatchProcessing\%TEST_NO%.properties" "%TEST_DIR_PATH%" "*.txt" "1.txt"
call %TEST_ASSERT_EQUALS% TEST%TEST_NO% 3 %ERRORLEVEL%
call %TEST_ASSERT_FILE_FIRST_LINE_EQUALS% TEST%TEST_NO%_1 "a" "%TEST_DIR_PATH%\1.txt"
call %TEST_ASSERT_FILE_FIRST_LINE_EQUALS% TEST%TEST_NO%_2 "b" "%TEST_DIR_PATH%\2.jpg"
call %TEST_ASSERT_FILE_FIRST_LINE_EQUALS% TEST%TEST_NO%_3 "c" "%TEST_DIR_PATH%\3.txt"
call %TEST_ASSERT_FILE_FIRST_LINE_EQUALS% TEST%TEST_NO%_4 "d" "%TEST_DIR_PATH%\4.txt"
call %TEST_ASSERT_FILE_FIRST_LINE_EQUALS% TEST%TEST_NO%_5 "e" "%TEST_DIR_PATH%\5"
call %TEST_ASSERT_FILE_FIRST_LINE_EQUALS% TEST%TEST_NO%_6 "f" "%TEST_DIR_PATH%\6.gif"

rem 6-2 3ファイルのうち2ファイル目でエラーが発生し処理を継続しない
set TEST_NO=6-2
set TEST_DIR_PATH=%TEST_TEMP_DIR_2%\%TEST_NO%
call :Test1 "%TEST_DIR_PATH%"
call %TEST_TARGET_PATH% "%~dp0\FileBatchProcessing\%TEST_NO%.properties" "%TEST_DIR_PATH%" "*.txt" "3.txt"
call %TEST_ASSERT_EQUALS% TEST%TEST_NO% 3 %ERRORLEVEL%
call %TEST_ASSERT_FILE_FIRST_LINE_EQUALS% TEST%TEST_NO%_1 "change" "%TEST_DIR_PATH%\1.txt"
call %TEST_ASSERT_FILE_FIRST_LINE_EQUALS% TEST%TEST_NO%_2 "b" "%TEST_DIR_PATH%\2.jpg"
call %TEST_ASSERT_FILE_FIRST_LINE_EQUALS% TEST%TEST_NO%_3 "c" "%TEST_DIR_PATH%\3.txt"
call %TEST_ASSERT_FILE_FIRST_LINE_EQUALS% TEST%TEST_NO%_4 "d" "%TEST_DIR_PATH%\4.txt"
call %TEST_ASSERT_FILE_FIRST_LINE_EQUALS% TEST%TEST_NO%_5 "e" "%TEST_DIR_PATH%\5"
call %TEST_ASSERT_FILE_FIRST_LINE_EQUALS% TEST%TEST_NO%_6 "f" "%TEST_DIR_PATH%\6.gif"

rem 6-3 3ファイルのうち3ファイル目でエラーが発生し処理を継続しない
set TEST_NO=6-3
set TEST_DIR_PATH=%TEST_TEMP_DIR_2%\%TEST_NO%
call :Test1 "%TEST_DIR_PATH%"
call %TEST_TARGET_PATH% "%~dp0\FileBatchProcessing\%TEST_NO%.properties" "%TEST_DIR_PATH%" "*.txt" "4.txt"
call %TEST_ASSERT_EQUALS% TEST%TEST_NO% 3 %ERRORLEVEL%
call %TEST_ASSERT_FILE_FIRST_LINE_EQUALS% TEST%TEST_NO%_1 "change" "%TEST_DIR_PATH%\1.txt"
call %TEST_ASSERT_FILE_FIRST_LINE_EQUALS% TEST%TEST_NO%_2 "b" "%TEST_DIR_PATH%\2.jpg"
call %TEST_ASSERT_FILE_FIRST_LINE_EQUALS% TEST%TEST_NO%_3 "change" "%TEST_DIR_PATH%\3.txt"
call %TEST_ASSERT_FILE_FIRST_LINE_EQUALS% TEST%TEST_NO%_4 "d" "%TEST_DIR_PATH%\4.txt"
call %TEST_ASSERT_FILE_FIRST_LINE_EQUALS% TEST%TEST_NO%_5 "e" "%TEST_DIR_PATH%\5"
call %TEST_ASSERT_FILE_FIRST_LINE_EQUALS% TEST%TEST_NO%_6 "f" "%TEST_DIR_PATH%\6.gif"

rem 6-4 3ファイルのうち1ファイル目でエラーが発生し処理を継続する
set TEST_NO=6-4
set TEST_DIR_PATH=%TEST_TEMP_DIR_2%\%TEST_NO%
call :Test1 "%TEST_DIR_PATH%"
call %TEST_TARGET_PATH% "%~dp0\FileBatchProcessing\%TEST_NO%.properties" "%TEST_DIR_PATH%" "*.txt" "1.txt"
call %TEST_ASSERT_EQUALS% TEST%TEST_NO% 3 %ERRORLEVEL%
call %TEST_ASSERT_FILE_FIRST_LINE_EQUALS% TEST%TEST_NO%_1 "a" "%TEST_DIR_PATH%\1.txt"
call %TEST_ASSERT_FILE_FIRST_LINE_EQUALS% TEST%TEST_NO%_2 "b" "%TEST_DIR_PATH%\2.jpg"
call %TEST_ASSERT_FILE_FIRST_LINE_EQUALS% TEST%TEST_NO%_3 "change" "%TEST_DIR_PATH%\3.txt"
call %TEST_ASSERT_FILE_FIRST_LINE_EQUALS% TEST%TEST_NO%_4 "change" "%TEST_DIR_PATH%\4.txt"
call %TEST_ASSERT_FILE_FIRST_LINE_EQUALS% TEST%TEST_NO%_5 "e" "%TEST_DIR_PATH%\5"
call %TEST_ASSERT_FILE_FIRST_LINE_EQUALS% TEST%TEST_NO%_6 "f" "%TEST_DIR_PATH%\6.gif"

rem 6-5 3ファイルのうち2ファイル目でエラーが発生し処理を継続する
set TEST_NO=6-5
set TEST_DIR_PATH=%TEST_TEMP_DIR_2%\%TEST_NO%
call :Test1 "%TEST_DIR_PATH%"
call %TEST_TARGET_PATH% "%~dp0\FileBatchProcessing\%TEST_NO%.properties" "%TEST_DIR_PATH%" "*.txt" "3.txt"
call %TEST_ASSERT_EQUALS% TEST%TEST_NO% 3 %ERRORLEVEL%
call %TEST_ASSERT_FILE_FIRST_LINE_EQUALS% TEST%TEST_NO%_1 "change" "%TEST_DIR_PATH%\1.txt"
call %TEST_ASSERT_FILE_FIRST_LINE_EQUALS% TEST%TEST_NO%_2 "b" "%TEST_DIR_PATH%\2.jpg"
call %TEST_ASSERT_FILE_FIRST_LINE_EQUALS% TEST%TEST_NO%_3 "c" "%TEST_DIR_PATH%\3.txt"
call %TEST_ASSERT_FILE_FIRST_LINE_EQUALS% TEST%TEST_NO%_4 "change" "%TEST_DIR_PATH%\4.txt"
call %TEST_ASSERT_FILE_FIRST_LINE_EQUALS% TEST%TEST_NO%_5 "e" "%TEST_DIR_PATH%\5"
call %TEST_ASSERT_FILE_FIRST_LINE_EQUALS% TEST%TEST_NO%_6 "f" "%TEST_DIR_PATH%\6.gif"

rem 6-6 3ファイルのうち3ファイル目でエラーが発生し処理を継続する
set TEST_NO=6-6
set TEST_DIR_PATH=%TEST_TEMP_DIR_2%\%TEST_NO%
call :Test1 "%TEST_DIR_PATH%"
call %TEST_TARGET_PATH% "%~dp0\FileBatchProcessing\%TEST_NO%.properties" "%TEST_DIR_PATH%" "*.txt" "4.txt"
call %TEST_ASSERT_EQUALS% TEST%TEST_NO% 3 %ERRORLEVEL%
call %TEST_ASSERT_FILE_FIRST_LINE_EQUALS% TEST%TEST_NO%_1 "change" "%TEST_DIR_PATH%\1.txt"
call %TEST_ASSERT_FILE_FIRST_LINE_EQUALS% TEST%TEST_NO%_2 "b" "%TEST_DIR_PATH%\2.jpg"
call %TEST_ASSERT_FILE_FIRST_LINE_EQUALS% TEST%TEST_NO%_3 "change" "%TEST_DIR_PATH%\3.txt"
call %TEST_ASSERT_FILE_FIRST_LINE_EQUALS% TEST%TEST_NO%_4 "d" "%TEST_DIR_PATH%\4.txt"
call %TEST_ASSERT_FILE_FIRST_LINE_EQUALS% TEST%TEST_NO%_5 "e" "%TEST_DIR_PATH%\5"
call %TEST_ASSERT_FILE_FIRST_LINE_EQUALS% TEST%TEST_NO%_6 "f" "%TEST_DIR_PATH%\6.gif"

rd /s /q %TEST_TEMP_DIR_2%

endlocal
pause

exit /b

:Test1
setlocal
set TEST_DIR_PATH=%~1
mkdir "%TEST_DIR_PATH%"
echo a> "%TEST_DIR_PATH%\1.txt"
echo b> "%TEST_DIR_PATH%\2.jpg"
echo c> "%TEST_DIR_PATH%\3.txt"
echo d> "%TEST_DIR_PATH%\4.txt"
echo e> "%TEST_DIR_PATH%\5"
echo f> "%TEST_DIR_PATH%\6.gif"
endlocal
exit /b
