@setlocal
@echo off

call "%~dp0\test-config.bat"

rem テスト対象
set TEST_TARGET_PATH=%TEST_BAT_DIR%\IsInteger.bat

rem TEST1 整数の場合、0を返す
rem TEST1-1 記号無し1桁
call %TEST_TARGET_PATH% 5
call %TEST_ASSERT_EQUALS% TEST1-1 0 %ERRORLEVEL%

rem TEST1-2 記号無し3桁
call %TEST_TARGET_PATH% 236
call %TEST_ASSERT_EQUALS% TEST1-2 0 %ERRORLEVEL%

rem TEST1-3 +記号1桁
call %TEST_TARGET_PATH% +4
call %TEST_ASSERT_EQUALS% TEST1-3 0 %ERRORLEVEL%

rem TEST1-4 +記号3桁
call %TEST_TARGET_PATH% +987
call %TEST_ASSERT_EQUALS% TEST1-4 0 %ERRORLEVEL%

rem TEST1-5 -記号1桁
call %TEST_TARGET_PATH% -8
call %TEST_ASSERT_EQUALS% TEST1-5 0 %ERRORLEVEL%

rem TEST1-6 -記号3桁
call %TEST_TARGET_PATH% -567
call %TEST_ASSERT_EQUALS% TEST1-6 0 %ERRORLEVEL%

rem TEST2 整数以外の場合、1を返す
rem TEST2-1 記号無し1桁
call %TEST_TARGET_PATH% h
call %TEST_ASSERT_EQUALS% TEST2-1 1 %ERRORLEVEL%

rem TEST2-2 記号無し3桁
call %TEST_TARGET_PATH% o12
call %TEST_ASSERT_EQUALS% TEST2-2 1 %ERRORLEVEL%

rem TEST2-3 +記号あり1桁
call %TEST_TARGET_PATH% +a
call %TEST_ASSERT_EQUALS% TEST2-3 1 %ERRORLEVEL%

rem TEST2-4 +記号あり3桁
call %TEST_TARGET_PATH% +x12
call %TEST_ASSERT_EQUALS% TEST2-4 1 %ERRORLEVEL%

rem TEST2-5 -記号あり1桁
call %TEST_TARGET_PATH% -z
call %TEST_ASSERT_EQUALS% TEST2-5 1 %ERRORLEVEL%

rem TEST2-6 +記号あり3桁
call %TEST_TARGET_PATH% -m75
call %TEST_ASSERT_EQUALS% TEST2-6 1 %ERRORLEVEL%

rem TEST2-7
call %TEST_TARGET_PATH% 1+
call %TEST_ASSERT_EQUALS% TEST2-7 1 %ERRORLEVEL%

rem TEST2-8
call %TEST_TARGET_PATH% 1-
call %TEST_ASSERT_EQUALS% TEST2-8 1 %ERRORLEVEL%

rem TEST2-9
call %TEST_TARGET_PATH% +-1
call %TEST_ASSERT_EQUALS% TEST2-9 1 %ERRORLEVEL%

rem TEST2-10
call %TEST_TARGET_PATH% -+1
call %TEST_ASSERT_EQUALS% TEST2-10 1 %ERRORLEVEL%

rem TEST2-11 NULL
call %TEST_TARGET_PATH% 
call %TEST_ASSERT_EQUALS% TEST2-11 1 %ERRORLEVEL%

endlocal
pause

exit /b
