@setlocal
@echo off

call "%~dp0\test-config.bat"

rem テスト対象
set TEST_TARGET_PATH="%TEST_BAT_DIR%\Logger.bat"
set TEST_DATA_DIR=%TEST_HOME_DIR%\Logger

set LOGGER_LEVEL=
set LOGGER_HANDLER=
set LOGGER_FILE_OUTPUT=
set LOGGER_FILE_ROTATE=
set LOGGER_FILE_ROTATE_MAXSIZE=

rem ログ出力先コンソール
rem 1 ログレベルTRACE
setlocal
set TESTNO=1
set LOGGER_LEVEL=traCe
set LOGGER_HANDLER=console
echo %TESTNO% Expected: trace debug info warn error fatal
call %TEST_TARGET_PATH% trace "%TESTNO%-1 OK trace"
call %TEST_TARGET_PATH% Debug "%TESTNO%-2 OK debug"
call %TEST_TARGET_PATH% INFO "%TESTNO%-3 OK info"
call %TEST_TARGET_PATH% WARn "%TESTNO%-4 OK warn"
call %TEST_TARGET_PATH% error "%TESTNO%-5 OK error"
call %TEST_TARGET_PATH% fatal "%TESTNO%-6 OK fatal"
call %TEST_TARGET_PATH% hoge "%TESTNO%-7 NG hoge"
endlocal

rem 2 ログレベルDEBUG
setlocal
set TESTNO=2
set LOGGER_LEVEL=DeBUG
set LOGGER_HANDLER=Console
echo %TESTNO% Expected: debug info warn error fatal
call %TEST_TARGET_PATH% trace "%TESTNO%-1 NG trace"
call %TEST_TARGET_PATH% Debug "%TESTNO%-2 OK debug"
call %TEST_TARGET_PATH% INFO "%TESTNO%-3 OK info"
call %TEST_TARGET_PATH% WARn "%TESTNO%-4 OK warn"
call %TEST_TARGET_PATH% error "%TESTNO%-5 OK error"
call %TEST_TARGET_PATH% fatal "%TESTNO%-6 OK fatal"
call %TEST_TARGET_PATH% hoge "%TESTNO%-7 NG hoge"
endlocal

rem 3 ログレベルINFO
setlocal
set TESTNO=3
set LOGGER_LEVEL=INFO
set LOGGER_HANDLER=CONSOLE
echo %TESTNO% Expected: info warn error fatal
call %TEST_TARGET_PATH% trace "%TESTNO%-1 NG trace"
call %TEST_TARGET_PATH% Debug "%TESTNO%-2 NG debug"
call %TEST_TARGET_PATH% INFO "%TESTNO%-3 OK info"
call %TEST_TARGET_PATH% WARn "%TESTNO%-4 OK warn"
call %TEST_TARGET_PATH% error "%TESTNO%-5 OK error"
call %TEST_TARGET_PATH% fatal "%TESTNO%-6 OK fatal"
call %TEST_TARGET_PATH% hoge "%TESTNO%-7 NG hoge"
endlocal

rem 4 ログレベルWARN
setlocal
set TESTNO=4
set LOGGER_LEVEL=WARN
set LOGGER_HANDLER=CONSOLE
echo %TESTNO% Expected: warn error fatal
call %TEST_TARGET_PATH% trace "%TESTNO%-1 NG trace"
call %TEST_TARGET_PATH% Debug "%TESTNO%-2 NG debug"
call %TEST_TARGET_PATH% INFO "%TESTNO%-3 NG info"
call %TEST_TARGET_PATH% WARn "%TESTNO%-4 OK warn"
call %TEST_TARGET_PATH% error "%TESTNO%-5 OK error"
call %TEST_TARGET_PATH% fatal "%TESTNO%-6 OK fatal"
call %TEST_TARGET_PATH% hoge "%TESTNO%-7 NG hoge"
endlocal

rem 5 ログレベルERROR
setlocal
set TESTNO=5
set LOGGER_LEVEL=ERROR
set LOGGER_HANDLER=CONSOLE
echo %TESTNO% Expected: error fatal
call %TEST_TARGET_PATH% trace "%TESTNO%-1 NG trace"
call %TEST_TARGET_PATH% Debug "%TESTNO%-2 NG debug"
call %TEST_TARGET_PATH% INFO "%TESTNO%-3 NG info"
call %TEST_TARGET_PATH% WARn "%TESTNO%-4 NG warn"
call %TEST_TARGET_PATH% error "%TESTNO%-5 OK error"
call %TEST_TARGET_PATH% fatal "%TESTNO%-6 OK fatal"
call %TEST_TARGET_PATH% hoge "%TESTNO%-7 NG hoge"
endlocal

rem 6 ログレベルFATAL
setlocal
set TESTNO=6
set LOGGER_LEVEL=FATAL
set LOGGER_HANDLER=CONSOLE
echo %TESTNO% Expected: fatal
call %TEST_TARGET_PATH% trace "%TESTNO%-1 NG trace"
call %TEST_TARGET_PATH% Debug "%TESTNO%-2 NG debug"
call %TEST_TARGET_PATH% INFO "%TESTNO%-3 NG info"
call %TEST_TARGET_PATH% WARn "%TESTNO%-4 NG warn"
call %TEST_TARGET_PATH% error "%TESTNO%-5 NG error"
call %TEST_TARGET_PATH% fatal "%TESTNO%-6 OK fatal"
call %TEST_TARGET_PATH% hoge "%TESTNO%-7 NG hoge"
endlocal

rem 7 ログレベル不正
setlocal
set TESTNO=7
set LOGGER_LEVEL=hoge
set LOGGER_HANDLER=CONSOLE
echo %TESTNO% Expected: No log
call %TEST_TARGET_PATH% trace "%TESTNO%-1 NG trace"
call %TEST_TARGET_PATH% Debug "%TESTNO%-2 NG debug"
call %TEST_TARGET_PATH% INFO "%TESTNO%-3 NG info"
call %TEST_TARGET_PATH% WARn "%TESTNO%-4 NG warn"
call %TEST_TARGET_PATH% error "%TESTNO%-5 NG error"
call %TEST_TARGET_PATH% fatal "%TESTNO%-6 NG fatal"
call %TEST_TARGET_PATH% hoge "%TESTNO%-7 NG hoge"
endlocal

rem 8 引数ログレベル未指定
setlocal
set TESTNO=8
set LOGGER_LEVEL=INFO
set LOGGER_HANDLER=CONSOLE
echo %TESTNO% Expected: No log
set LEVEL=
call %TEST_TARGET_PATH%
call "%TEST_ASSERT_EQUALS%" "%TESTNO%" 1 %ERRORLEVEL%
endlocal

rem 9 引数メッセージ未指定
setlocal
set TESTNO=9
set LOGGER_LEVEL=INFO
set LOGGER_HANDLER=CONSOLE
echo %TESTNO% Expected: No log
call %TEST_TARGET_PATH% error
call "%TEST_ASSERT_EQUALS%" "%TESTNO%" 1 %ERRORLEVEL%
endlocal

rem 10 ログレベルが未指定
setlocal
set TESTNO=10
set LOGGER_LEVEL=
set LOGGER_HANDLER=CONSOLE
echo %TESTNO% Expected: No log
call %TEST_TARGET_PATH% error "%TESTNO%-5 NG error"
call "%TEST_ASSERT_EQUALS%" "%TESTNO%" 1 %ERRORLEVEL%
endlocal

rem 11 出力先が未指定
setlocal
set TESTNO=11
set LOGGER_LEVEL=INFO
set LOGGER_HANDLER=
echo %TESTNO% Expected: No log
call %TEST_TARGET_PATH% error "%TESTNO%-5 NG error"
call "%TEST_ASSERT_EQUALS%" "%TESTNO%" 1 %ERRORLEVEL%
endlocal

rem 12 出力先が不正
setlocal
set TESTNO=12
set LOGGER_LEVEL=INFO
set LOGGER_HANDLER=HOGE
echo %TESTNO% Expected: No log
call %TEST_TARGET_PATH% error "%TESTNO%-5 NG error"
call "%TEST_ASSERT_EQUALS%" "%TESTNO%" 1 %ERRORLEVEL%
endlocal

rem ログ出力先ファイル
rem テンポラリ
set time2=%time: =0%
set TEST_TEMP_DIR_2=%TEST_TEMP_DIR%\Logger_Test%date:~0,4%%date:~5,2%%date:~8,2%%time2:~0,2%%time2:~3,2%%time2:~6,2%%time2:~9,2%
mkdir "%TEST_TEMP_DIR_2%"

rem 100 ローテートなし ファイル無し
setlocal
set TESTNO=100
set LOGGER_LEVEL=INFO
set LOGGER_HANDLER=FILE
set LOGGER_FILE_OUTPUT="%TEST_TEMP_DIR_2%\%TESTNO%.log"
set LOGGER_FILE_ROTATE=SIZE
set LOGGER_FILE_ROTATE_MAXNUMBER=100
set LOGGER_FILE_ROTATE_MAXSIZE=10
echo %TESTNO% Expected: info warn error fatal
call %TEST_TARGET_PATH% trace "%TESTNO%-1 NG trace 日本語"
call %TEST_TARGET_PATH% Debug "%TESTNO%-2 NG debug 日本語"
call %TEST_TARGET_PATH% INFO "%TESTNO%-3 OK info 日本語"
call %TEST_TARGET_PATH% WARn "%TESTNO%-4 OK warn 日本語"
call %TEST_TARGET_PATH% error "%TESTNO%-5 OK error 日本語"
call %TEST_TARGET_PATH% fatal "%TESTNO%-6 OK fatal 日本語"
call %TEST_TARGET_PATH% hoge "%TESTNO%-7 NG hoge 日本語"
call %TEST_ASSERT_FILE_EXISTS% "%TESTNO%" "%TEST_TEMP_DIR_2%\%TESTNO%.log"
endlocal

rem 101 ローテートなし ファイルあり
setlocal
set TESTNO=101
set LOGGER_LEVEL=INFO
set LOGGER_HANDLER=FILE
set LOGGER_FILE_OUTPUT="%TEST_TEMP_DIR_2%\%TESTNO%.log"
set LOGGER_FILE_ROTATE=SIZE
set LOGGER_FILE_ROTATE_MAXNUMBER=100
set LOGGER_FILE_ROTATE_MAXSIZE=20
echo %TESTNO% Expected: info warn error fatal
copy "%TEST_DATA_DIR%\10kb.log" "%TEST_TEMP_DIR_2%\%TESTNO%.log"
call %TEST_TARGET_PATH% trace "%TESTNO%-1 NG trace 日本語"
call %TEST_TARGET_PATH% Debug "%TESTNO%-2 NG debug 日本語"
call %TEST_TARGET_PATH% INFO "%TESTNO%-3 OK info 日本語"
call %TEST_TARGET_PATH% WARn "%TESTNO%-4 OK warn 日本語"
call %TEST_TARGET_PATH% error "%TESTNO%-5 OK error 日本語"
call %TEST_TARGET_PATH% fatal "%TESTNO%-6 OK fatal 日本語"
call %TEST_TARGET_PATH% hoge "%TESTNO%-7 NG hoge 日本語"
call %TEST_ASSERT_FILE_FIRST_LINE_EQUALS% "%TESTNO%" "xx34567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890" "%TEST_TEMP_DIR_2%\%TESTNO%.log"
call %TEST_ASSERT_FILE_NOT_EXISTS% "%TESTNO%" "%TEST_TEMP_DIR_2%\%TESTNO%.log.1"
endlocal

rem 102 ローテートあり
setlocal
set TESTNO=102
set LOGGER_LEVEL=INFO
set LOGGER_HANDLER=FILE
set LOGGER_FILE_OUTPUT="%TEST_TEMP_DIR_2%\%TESTNO%.log"
set LOGGER_FILE_ROTATE=SIZE
set LOGGER_FILE_ROTATE_MAXNUMBER=100
set LOGGER_FILE_ROTATE_MAXSIZE=10
echo %TESTNO% Expected: info warn error fatal
copy "%TEST_DATA_DIR%\10kb.log" "%TEST_TEMP_DIR_2%\%TESTNO%.log"
call %TEST_TARGET_PATH% trace "%TESTNO%-1 NG trace 日本語"
call %TEST_TARGET_PATH% Debug "%TESTNO%-2 NG debug 日本語"
call %TEST_TARGET_PATH% INFO "%TESTNO%-3 OK info 日本語"
call %TEST_TARGET_PATH% WARn "%TESTNO%-4 OK warn 日本語"
call %TEST_TARGET_PATH% error "%TESTNO%-5 OK error 日本語"
call %TEST_TARGET_PATH% fatal "%TESTNO%-6 OK fatal 日本語"
call %TEST_TARGET_PATH% hoge "%TESTNO%-7 NG hoge 日本語"
call %TEST_ASSERT_FILE_EXISTS% "%TESTNO%" "%TEST_TEMP_DIR_2%\%TESTNO%.log"
call %TEST_ASSERT_FILE_FIRST_LINE_EQUALS% "%TESTNO%" "xx34567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890" "%TEST_TEMP_DIR_2%\%TESTNO%.log.1"
endlocal

rem 103 ローテート失敗
setlocal
set TESTNO=103
set LOGGER_LEVEL=INFO
set LOGGER_HANDLER=FILE
set LOGGER_FILE_OUTPUT="%TEST_TEMP_DIR_2%\%TESTNO%.log"
set LOGGER_FILE_ROTATE=SIZE
set LOGGER_FILE_ROTATE_MAXNUMBER=100
set LOGGER_FILE_ROTATE_MAXSIZE=10
echo %TESTNO% Expected: info warn error fatal
copy "%TEST_DATA_DIR%\10kb.log" "%TEST_TEMP_DIR_2%\%TESTNO%.log"
rem pause
call %TEST_TARGET_PATH% INFO "%TESTNO% OK info 日本語"
rem call %TEST_ASSERT_EQUALS% "%TESTNO%" 2 %ERRORLEVEL%
rem call %TEST_ASSERT_FILE_FIRST_LINE_EQUALS% "%TESTNO%" "xx34567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890" "%TEST_TEMP_DIR_2%\%TESTNO%.log"
rem call %TEST_ASSERT_FILE_NOT_EXISTS% "%TESTNO%" "%TEST_TEMP_DIR_2%\%TESTNO%.log.1"
endlocal

rem 104 サイズ上限指定なし
setlocal
set TESTNO=104
set LOGGER_LEVEL=INFO
set LOGGER_HANDLER=FILE
set LOGGER_FILE_OUTPUT="%TEST_TEMP_DIR_2%\%TESTNO%.log"
set LOGGER_FILE_ROTATE=SIZE
set LOGGER_FILE_ROTATE_MAXNUMBER=100
set LOGGER_FILE_ROTATE_MAXSIZE=
echo %TESTNO% Expected: info warn error fatal
copy "%TEST_DATA_DIR%\10kb.log" "%TEST_TEMP_DIR_2%\%TESTNO%.log"
call %TEST_TARGET_PATH% INFO "%TESTNO% OK info 日本語"
call %TEST_ASSERT_EQUALS% "%TESTNO%" 1 %ERRORLEVEL%
call %TEST_ASSERT_FILE_FIRST_LINE_EQUALS% "%TESTNO%" "xx34567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890" "%TEST_TEMP_DIR_2%\%TESTNO%.log"
call %TEST_ASSERT_FILE_NOT_EXISTS% "%TESTNO%" "%TEST_TEMP_DIR_2%\%TESTNO%.log.1"
endlocal

rem 105 サイズ上限が0
setlocal
set TESTNO=105
set LOGGER_LEVEL=INFO
set LOGGER_HANDLER=FILE
set LOGGER_FILE_OUTPUT="%TEST_TEMP_DIR_2%\%TESTNO%.log"
set LOGGER_FILE_ROTATE=SIZE
set LOGGER_FILE_ROTATE_MAXNUMBER=100
set LOGGER_FILE_ROTATE_MAXSIZE=0
echo %TESTNO% Expected: info warn error fatal
copy "%TEST_DATA_DIR%\10kb.log" "%TEST_TEMP_DIR_2%\%TESTNO%.log"
call %TEST_TARGET_PATH% INFO "%TESTNO% OK info 日本語"
call %TEST_ASSERT_EQUALS% "%TESTNO%" 1 %ERRORLEVEL%
call %TEST_ASSERT_FILE_FIRST_LINE_EQUALS% "%TESTNO%" "xx34567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890" "%TEST_TEMP_DIR_2%\%TESTNO%.log"
call %TEST_ASSERT_FILE_NOT_EXISTS% "%TESTNO%" "%TEST_TEMP_DIR_2%\%TESTNO%.log.1"
endlocal

rem 106 サイズ上限が1
setlocal
set TESTNO=106
set LOGGER_LEVEL=INFO
set LOGGER_HANDLER=FILE
set LOGGER_FILE_OUTPUT="%TEST_TEMP_DIR_2%\%TESTNO%.log"
set LOGGER_FILE_ROTATE=SIZE
set LOGGER_FILE_ROTATE_MAXNUMBER=100
set LOGGER_FILE_ROTATE_MAXSIZE=1
echo %TESTNO% Expected: info warn error fatal
copy "%TEST_DATA_DIR%\10kb.log" "%TEST_TEMP_DIR_2%\%TESTNO%.log"
call %TEST_TARGET_PATH% INFO "%TESTNO% OK info 日本語"
call %TEST_ASSERT_EQUALS% "%TESTNO%" 0 %ERRORLEVEL%
call %TEST_ASSERT_FILE_EXISTS% "%TESTNO%" "%TEST_TEMP_DIR_2%\%TESTNO%.log"
call %TEST_ASSERT_FILE_FIRST_LINE_EQUALS% "%TESTNO%" "xx34567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890" "%TEST_TEMP_DIR_2%\%TESTNO%.log.1"
endlocal

rem 107 サイズ上限が-1
setlocal
set TESTNO=107
set LOGGER_LEVEL=INFO
set LOGGER_HANDLER=FILE
set LOGGER_FILE_OUTPUT="%TEST_TEMP_DIR_2%\%TESTNO%.log"
set LOGGER_FILE_ROTATE=SIZE
set LOGGER_FILE_ROTATE_MAXNUMBER=100
set LOGGER_FILE_ROTATE_MAXSIZE=-1
echo %TESTNO% Expected: info warn error fatal
copy "%TEST_DATA_DIR%\10kb.log" "%TEST_TEMP_DIR_2%\%TESTNO%.log"
call %TEST_TARGET_PATH% INFO "%TESTNO% OK info 日本語"
call %TEST_ASSERT_EQUALS% "%TESTNO%" 1 %ERRORLEVEL%
call %TEST_ASSERT_FILE_FIRST_LINE_EQUALS% "%TESTNO%" "xx34567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890" "%TEST_TEMP_DIR_2%\%TESTNO%.log"
call %TEST_ASSERT_FILE_NOT_EXISTS% "%TESTNO%" "%TEST_TEMP_DIR_2%\%TESTNO%.log.1"
endlocal

rem 108 バックアップ数上限が指定なし
setlocal
set TESTNO=108
set LOGGER_LEVEL=INFO
set LOGGER_HANDLER=FILE
set LOGGER_FILE_OUTPUT="%TEST_TEMP_DIR_2%\%TESTNO%.log"
set LOGGER_FILE_ROTATE=SIZE
set LOGGER_FILE_ROTATE_MAXNUMBER=
set LOGGER_FILE_ROTATE_MAXSIZE=10
echo %TESTNO% Expected: info warn error fatal
copy "%TEST_DATA_DIR%\10kb.log" "%TEST_TEMP_DIR_2%\%TESTNO%.log"
call %TEST_TARGET_PATH% INFO "%TESTNO% OK info 日本語"
call %TEST_ASSERT_EQUALS% "%TESTNO%" 1 %ERRORLEVEL%
call %TEST_ASSERT_FILE_FIRST_LINE_EQUALS% "%TESTNO%" "xx34567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890" "%TEST_TEMP_DIR_2%\%TESTNO%.log"
call %TEST_ASSERT_FILE_NOT_EXISTS% "%TESTNO%" "%TEST_TEMP_DIR_2%\%TESTNO%.log.1"
endlocal

rem 109 バックアップ数上限が0
setlocal
set TESTNO=109
set LOGGER_LEVEL=INFO
set LOGGER_HANDLER=FILE
set LOGGER_FILE_OUTPUT="%TEST_TEMP_DIR_2%\%TESTNO%.log"
set LOGGER_FILE_ROTATE=SIZE
set LOGGER_FILE_ROTATE_MAXNUMBER=0
set LOGGER_FILE_ROTATE_MAXSIZE=10
echo %TESTNO% Expected: info warn error fatal
copy "%TEST_DATA_DIR%\10kb.log" "%TEST_TEMP_DIR_2%\%TESTNO%.log"
call %TEST_TARGET_PATH% INFO "%TESTNO% OK info 日本語"
call %TEST_ASSERT_EQUALS% "%TESTNO%" 1 %ERRORLEVEL%
call %TEST_ASSERT_FILE_FIRST_LINE_EQUALS% "%TESTNO%" "xx34567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890" "%TEST_TEMP_DIR_2%\%TESTNO%.log"
call %TEST_ASSERT_FILE_NOT_EXISTS% "%TESTNO%" "%TEST_TEMP_DIR_2%\%TESTNO%.log.1"
endlocal

rem 110 バックアップ数上限が1
setlocal
set TESTNO=110
set LOGGER_LEVEL=INFO
set LOGGER_HANDLER=FILE
set LOGGER_FILE_OUTPUT="%TEST_TEMP_DIR_2%\%TESTNO%.log"
set LOGGER_FILE_ROTATE=SIZE
set LOGGER_FILE_ROTATE_MAXNUMBER=1
set LOGGER_FILE_ROTATE_MAXSIZE=10
echo %TESTNO% Expected: info warn error fatal
copy "%TEST_DATA_DIR%\10kb.log" "%TEST_TEMP_DIR_2%\%TESTNO%.log"
echo hoge>> "%TEST_TEMP_DIR_2%\%TESTNO%.log.1"
call %TEST_TARGET_PATH% INFO "%TESTNO% OK info 日本語"
call %TEST_ASSERT_EQUALS% "%TESTNO%" 0 %ERRORLEVEL%
call %TEST_ASSERT_FILE_EXISTS% "%TESTNO%" "%TEST_TEMP_DIR_2%\%TESTNO%.log"
call %TEST_ASSERT_FILE_FIRST_LINE_EQUALS% "%TESTNO%" "xx34567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890" "%TEST_TEMP_DIR_2%\%TESTNO%.log.1"
call %TEST_ASSERT_FILE_NOT_EXISTS% "%TESTNO%" "%TEST_TEMP_DIR_2%\%TESTNO%.log.2"
endlocal

rem 111 バックアップ数上限が-1
setlocal
set TESTNO=111
set LOGGER_LEVEL=INFO
set LOGGER_HANDLER=FILE
set LOGGER_FILE_OUTPUT="%TEST_TEMP_DIR_2%\%TESTNO%.log"
set LOGGER_FILE_ROTATE=SIZE
set LOGGER_FILE_ROTATE_MAXNUMBER=-1
set LOGGER_FILE_ROTATE_MAXSIZE=10
echo %TESTNO% Expected: info warn error fatal
copy "%TEST_DATA_DIR%\10kb.log" "%TEST_TEMP_DIR_2%\%TESTNO%.log"
call %TEST_TARGET_PATH% INFO "%TESTNO% OK info 日本語"
call %TEST_ASSERT_EQUALS% "%TESTNO%" 1 %ERRORLEVEL%
call %TEST_ASSERT_FILE_FIRST_LINE_EQUALS% "%TESTNO%" "xx34567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890" "%TEST_TEMP_DIR_2%\%TESTNO%.log"
call %TEST_ASSERT_FILE_NOT_EXISTS% "%TESTNO%" "%TEST_TEMP_DIR_2%\%TESTNO%.log.1"
endlocal

rem 112 ローテート方式が未指定
setlocal
set TESTNO=112
set LOGGER_LEVEL=INFO
set LOGGER_HANDLER=FILE
set LOGGER_FILE_OUTPUT="%TEST_TEMP_DIR_2%\%TESTNO%.log"
set LOGGER_FILE_ROTATE=
set LOGGER_FILE_ROTATE_MAXNUMBER=
set LOGGER_FILE_ROTATE_MAXSIZE=
echo %TESTNO% Expected: info warn error fatal
copy "%TEST_DATA_DIR%\10kb.log" "%TEST_TEMP_DIR_2%\%TESTNO%.log"
call %TEST_TARGET_PATH% trace "%TESTNO%-1 NG trace 日本語"
call %TEST_TARGET_PATH% Debug "%TESTNO%-2 NG debug 日本語"
call %TEST_TARGET_PATH% INFO "%TESTNO%-3 OK info 日本語"
call %TEST_TARGET_PATH% WARn "%TESTNO%-4 OK warn 日本語"
call %TEST_TARGET_PATH% error "%TESTNO%-5 OK error 日本語"
call %TEST_TARGET_PATH% fatal "%TESTNO%-6 OK fatal 日本語"
call %TEST_TARGET_PATH% hoge "%TESTNO%-7 NG hoge 日本語"
call %TEST_ASSERT_FILE_FIRST_LINE_EQUALS% "%TESTNO%" "xx34567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890" "%TEST_TEMP_DIR_2%\%TESTNO%.log"
call %TEST_ASSERT_FILE_NOT_EXISTS% "%TESTNO%" "%TEST_TEMP_DIR_2%\%TESTNO%.log.1"
endlocal

rd /s /q %TEST_TEMP_DIR_2%

endlocal
pause

exit /b
